_open_tour_lib:
    resource: '@ApothanOpenTourLibBundle/config/routes/'
    type: directory
    prefix: /OT


#_open_tours_default:
#    resource: '@ApothanOpenToursBundle/Controller/DefaultController.php'
#    type: annotation
#    prefix: /OTF
